import { z } from 'zod';
export const categories = ['Кухни','Шкафы','Тумбы и ТВ зона','Гардеробные','Детская комната','Мебель для ванной'];
export const materials = ['ЛДСП Egger','МДФ 16 в пленке','МДФ в пленке с фрезеровкой','МДФ Эмаль','Алвик','Шпон','МДФ в пластике'];
export const configs = [ ['Прямая','Угловая','П-образная','С островом','С пеналами','Другое'], ['Распашные','Купе'], ['Тумба под ТВ','Панель с тумбой','С навесными шкафами','С полками','С закрытым хранением','Другое'], ['Линейная','Угловая','П-образная','Встроенная','Открытая','Закрытая','Другое'], ['Рабочая зона','Шкаф','Стеллаж','Кровать с хранением','Комплект','Другое'], ['Тумба под раковину','Пенал','Зеркальный шкаф','Комплект','Подвесная мебель','Другое'] ];
export const options = [ ['Подсветка','Фартук','Мойка и смеситель','Встроенная техника','Витрина','Доставка','Монтаж'], ['Подсветка','Зеркало','Стекло','Доставка','Монтаж'], ['Подсветка','Витрина','Доставка','Монтаж'], ['Подсветка','Зеркало','Доставка','Монтаж'], ['Подсветка','Доставка','Монтаж'], ['Подсветка','Зеркало','Доставка','Монтаж'] ];
export const dimLabels = [['Длина кухни','Высота кухни','Глубина нижних модулей'],['Ширина шкафа','Высота шкафа','Глубина шкафа'],['Ширина ТВ-зоны','Высота композиции','Глубина тумб и секций'],['Длина системы','Высота системы','Глубина секций'],['Ширина зоны','Высота мебели','Глубина мебели'],['Ширина мебели','Высота мебели','Глубина мебели']];
export const woods = ['Орех','Дуб','Ясень','Бук'];
export const woodDescriptions = ['Тёплый шоколадный','Золотисто-медовый','Светлый, выразительный','Ровный розово-бежевый'];
export const counters = ['Полки','Двери','Ящики'];
export const decorations = ['Карниз сверху','Пилястры по бокам','Филёнчатые фасады','Фигурный фартук / царга'];
export const countertops = ['Не выбрана — рассчитать отдельно','ЛДСП','Керамогранит','Натуральный камень','Акрил','Алвик','HPL compact'];
export const ranges = (cat:number) => cat === 1 ? [[60,320,1],[180,260,1],[40,75,1]] : [[80,900,10],[80,320,10],[30,120,5]];
export const limits = {shelves:30,drawers:20,doors:20}; // Editable prototype limits, not manufacturing constraints.
export const configSchema = z.object({cat:z.number().int().min(0).max(5),dims:z.tuple([z.number(),z.number(),z.number()]),material:z.enum(materials as [string,...string[]]),configuration:z.string(),hardware:z.enum(['Надежная базовая','Премиум']),extras:z.array(z.string()).max(7),counts:z.tuple([z.number().int().min(0).max(30),z.number().int().min(0).max(20),z.number().int().min(0).max(20)]),guides:z.enum(['Деревянные','Blum']),filling:z.boolean(),niche:z.boolean(),support:z.enum(['Цоколь','Ножки','Точёные']),supportHeight:z.number().int().min(4).max(30),handles:z.enum(['Кнопки','Рейлинг','Раковина','Без']),decor:z.array(z.string()).max(4),carving:z.enum(['Лаконичный','С резьбой']),wood:z.number().int().min(0).max(3),upper:z.enum(['720 мм','920 мм']),countertop:z.enum(countertops as [string,...string[]])}).superRefine((v,ctx)=>{v.dims.forEach((n,i)=>{const [min,max,step]=ranges(v.cat)[i];if(!Number.isFinite(n)||n<min||n>max||(n-min)%step!==0)ctx.addIssue({code:'custom',message:'Проверьте размеры',path:['dims',i]});});if(!configs[v.cat].includes(v.configuration)||v.extras.some(x=>!options[v.cat].includes(x))||v.decor.some(x=>!decorations.includes(x)))ctx.addIssue({code:'custom',message:'Несовместимые параметры'});if(v.cat===1&&(v.counts[1]<1||v.counts[1]>6))ctx.addIssue({code:'custom',message:'Выберите от 1 до 6 дверей'});});
export type Config = z.infer<typeof configSchema>;
export const initial:Config = {cat:1,dims:[160,220,60],material:materials[0],configuration:'Распашные',hardware:'Надежная базовая',extras:[],counts:[5,3,2],guides:'Деревянные',filling:false,niche:false,support:'Цоколь',supportHeight:14,handles:'Раковина',decor:['Филёнчатые фасады'],carving:'Лаконичный',wood:0,upper:'720 мм',countertop:countertops[0]};
export const canDecor = (c:Config) => ['МДФ в пленке с фрезеровкой','МДФ Эмаль','Шпон'].includes(c.material);
export const effective = (c:Config) => ({...c,decor:canDecor(c)?c.decor:[],carving:canDecor(c)?c.carving:'Лаконичный',guides:c.counts[2]>0?c.guides:null,upper:c.cat===0?c.upper:null,countertop:c.cat===0?c.countertop:null,extras:c.extras.filter(x=>options[c.cat].includes(x))});
export const contactSchema = z.object({email:z.string().trim().max(254),phone:z.string().trim().max(40),social:z.string().trim().max(500)}).superRefine((v,ctx)=>{if(!v.email&&!v.phone&&!v.social)ctx.addIssue({code:'custom',message:'Укажите хотя бы один способ связи'});if(v.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.email))ctx.addIssue({code:'custom',message:'Проверьте электронную почту',path:['email']});if(v.phone&&!/^\+?[\d\s()\-]+$/.test(v.phone)||v.phone&&(v.phone.replace(/\D/g,'').length<10||v.phone.replace(/\D/g,'').length>15))ctx.addIssue({code:'custom',message:'Укажите телефон с кодом страны',path:['phone']});if(v.social){try{const u=new URL(v.social);if(!['http:','https:'].includes(u.protocol)||!u.hostname.includes('.'))throw 0;}catch{ctx.addIssue({code:'custom',message:'Введите полную ссылку, начиная с https://',path:['social']});}}});
